Remove URLSanitizer from app chooser dialogue
dic1911/android_URLSanitizer pull request #6
Opened 2021-02-13 12:00 UTC by potato-stew

Currently, clicking URLSanitizer on the app chooser dialogue sends another intent with the sanitized URL. With this change, URLSanitizer will not appear among the list of apps for the sanitized URL.

Works by customizing intents passed to Intent.createChooser() and removing our app among the list.

2021-02-13 15:49 UTC, dic1911 commented
Thanks for the improvement, I'm not on my PC these days, will definitely test/review this later.

2021-02-14 07:40 UTC, dic1911 requested changes

2021-02-14 07:40 UTC, dic1911 commented on app/src/main/java/moe/dic1911/urlsanitizer/MainActivity.java
> +        if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
Please remove the space before `Build.VERSION.SDK_INT`

2021-02-14 07:40 UTC, dic1911 commented on app/src/main/java/moe/dic1911/urlsanitizer/MainActivity.java
> +        List <ResolveInfo> resolvedActivities = getPackageManager().queryIntentActivities(rawIntent,0);//PackageManager.MATCH_ALL);
Please remove `//PackageManager.MATCH_ALL);`

2021-02-14 07:40 UTC, dic1911 commented on app/src/main/java/moe/dic1911/urlsanitizer/MainActivity.java
> +    protected boolean isDefaultBrowser () {
This function is unused right?
Please remove this as well.

2021-02-18 16:01 UTC, potato-stew commented
Are the changes fine?

Also I was planning of adding another feature to make URLSanitizer the default browser app. Currently if its the default browser, it does not get to populate the browser llist and remove itself, but is directly called by the OS. This causes it to be stuck in an infinite loop.

My idea is to is to check if our app is the default browser. If its not, current behavior will do. If it is the default, then we will create a floating list (possibly bottom-aligned) of all browsers except URLSanitizer to open the sanitized link in. We could also have our app select a default browser to open sanitized links in. Basically emulate the intent chooser ourselves if URLSanitizer is the default browser. How does that sound?

2021-02-18 16:10 UTC, dic1911 commented
Yeah that sounds nice, and since the code is cleaned, I'm now merging and closing this PR.

2021-02-18 16:10 UTC, merged